=== solvo-ru/yard-apidoc/models/schemas/cargo-data.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Груз",
  "type": "object",
  "description": "Объект системы, содержащий информацию о перевозимом грузе.",


  "required": [
    "num",
    "desc",
    "amount",
    "weight",
    "package",
    "owner"
  ],
  "examples": [
  {
    "num": "Груз-001",
    "desc": "Электроника",
    "amount": 10,
    "weight": 50,
    "volume": 0.5,
    "package": "Коробка",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174000",
      "entity": "item"
    }
  },
  {
    "num": "Груз-002",
    "desc": "Товары народного потребления",
    "amount": 20,
    "weight": 100,
    "volume": 1.2,
    "package": "Паллет",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174001",
      "entity": "item"
    }
  },
  {
    "num": "Груз-003",
    "desc": "Стройматериалы",
    "amount": 5,
    "weight": 200,
    "volume": 2.5,
    "package": "Биг-бэг",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174002",
      "entity": "item"
    }
  },
  {
    "num": "Груз-004",
    "desc": "Мебель",
    "amount": 3,
    "weight": 150,
    "volume": 1.8,
    "package": "Коробка",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174003",
      "entity": "item"
    }
  },
  {
    "num": "Груз-005",
    "desc": "Автомобильные запчасти",
    "amount": 15,
    "weight": 75,
    "volume": 0.8,
    "package": "Паллет",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174004",
      "entity": "item"
    }
  },
  {
    "num": "Груз-006",
    "desc": "Продукты питания",
    "amount": 10,
    "weight": 30,
    "volume": 0.3,
    "package": "Коробка",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174005",
      "entity": "item"
    }
  },
  {
    "num": "Груз-007",
    "desc": "Химические вещества",
    "amount": 5,
    "weight": 100,
    "volume": 1.5,
    "package": "Биг-бэг",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174006",
      "entity": "item"
    }
  },
  {
    "num": "Груз-008",
    "desc": "Электрическое оборудование",
    "amount": 8,
    "weight": 120,
    "volume": 1.2,
    "package": "Паллет",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174007",
      "entity": "item"
    }
  },
  {
    "num": "Груз-009",
    "desc": "Лекарственные препараты",
    "amount": 2,
    "weight": 20,
    "volume": 0.2,
    "package": "Коробка",
    "owner": {
      "host": "example.com",
      "id": "123e4567-e89b-12d3-a456-426614174008",
      "entity": "item"
    }
  }],
  "properties": {
    "num": {
      "type": "string",
      "description": "Идентификатор грузовой единицы"
    },
    "desc": {
      "type": "string",
      "description": "Текстовое описание груза"
    },
    "amount": {
      "type": "integer",
      "minimum": 1,
      "default": 1,
      "description": "Количество груза в единицах измерения (штуки)"
    },
    "weight": {
      "type": "integer",
      "minimum": 1,
      "description": "Суммарный вес груза в килограммах вместе с упаковкой (брутто)"
    },
    "volume": {
      "type": "number",
      "format": "float",
      "exclusiveMinimum": 0,
      "description": "Объем груза в метрах кубических. Вещественное число с тремя знаками после запятой."
    },
    "package": {
      "type": "string",
      "description": "Сведения об упаковке груза"
    },
    "owner": {
      "description": "Контрагент, являющийся владельцем перевозимого груза",
      "oneOf": [
        {
          "$ref": "../props/link.json"
        },
        {
          "$ref": "./contractor-item.json"
        }
      ]
    }
  }
}

=== solvo-ru/yard-apidoc/example_cargo-data.json
[
  {
    "num": "5ZMqzXS9I7J7oUQ",
    "desc": "SqN4P0P",
    "amount": 312,
    "weight": 144,
    "volume": 349.7,
    "package": "rRjAaT",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "sX4ea4z7PH",
    "desc": "rCiAKM9UOROU1c",
    "amount": 67,
    "weight": 976,
    "volume": 934.7,
    "package": "LRJzzsJVvJtgKvZf",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "at5CYDeX8Uz",
    "desc": "zYNb7uyraeakVEK",
    "amount": 949,
    "weight": 74,
    "volume": 497.14,
    "package": "zTkcRtECseac",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "IC1ZUXgDxc",
    "desc": "bg28Nl",
    "amount": 259,
    "weight": 118,
    "volume": 121.58,
    "package": "TiXQvn",
    "owner": {
      "error": "Unable to resolve reference: ./contractor-item.json"
    }
  },
  {
    "num": "PgOR5qnpb6r5ekWvf9",
    "desc": "m1UxdZOqoAEV7",
    "amount": 747,
    "weight": 187,
    "volume": 273.81,
    "package": "KSJVmx",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "XrljuxXxnUufB3O",
    "desc": "CKMv43",
    "amount": 417,
    "weight": 338,
    "volume": 401.12,
    "package": "kY8jubUUxVtYVTc0",
    "owner": {
      "error": "Unable to resolve reference: ./contractor-item.json"
    }
  },
  {
    "num": "AEHlJvubVLzP",
    "desc": "9H1ti8qAEq",
    "amount": 839,
    "weight": 797,
    "volume": 639.93,
    "package": "6TNEiyNYXB2G",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "iEpoe5Lt9DTH3",
    "desc": "jAsMALg",
    "amount": 24,
    "weight": 769,
    "volume": 517.0,
    "package": "w380772pRjy",
    "owner": {
      "error": "Unable to resolve reference: ./contractor-item.json"
    }
  },
  {
    "num": "BIaorlZg3JEwVX1Kx8",
    "desc": "hgcGm",
    "amount": 421,
    "weight": 416,
    "volume": 345.03,
    "package": "IjK5dFJx8gbiL",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  },
  {
    "num": "9ylTcxXA5NNs",
    "desc": "4cBIWkp5nrv",
    "amount": 83,
    "weight": 557,
    "volume": 176.89,
    "package": "0RD0EuUoqUVKmX",
    "owner": {
      "error": "Unable to resolve reference: ../props/link.json"
    }
  }
]
