=== solvo-ru/yard-apidoc/models/schemas/oauthtokenrequest.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "grant_type": {
      "type": "string",
      "enum": [
        "authorization_code",
        "refresh_token"
      ],
      "examples": [
        "authorization_code",
        "refresh_token",
        "authorization_code",
        "refresh_token",
        "authorization_code",
        "refresh_token"
      ]
    },
    "code": {
      "type": "string",
      "description": "Authorization code",
      "examples": [
        "SplxlOBeZQQYbYS6WxSbIA",
        "SplxlOBeZQQYbYS6WxSbIA",
        "SplxlOBeZQQYbYS6WxSbIA"
      ]
    },
    "redirect_uri": {
      "type": "string",
      "description": "Redirect URI",
      "examples": [
        "https://client.example.com/callback",
        "https://client.example.com/callback",
        "https://client.example.com/callback"
      ]
    },
    "client_id": {
      "type": "string",
      "description": "Client ID",
      "examples": [
        "s6BhdRkqt3",
        "s6BhdRkqt3",
        "s6BhdRkqt3"
      ]
    },
    "client_secret": {
      "type": "string",
      "description": "Client secret",
      "examples": [
        "7Fjfp0ZBr1KtDRbnfVdmIw",
        "7Fjfp0ZBr1KtDRbnfVdmIw",
        "7Fjfp0ZBr1KtDRbnfVdmIw"
      ]
    }
  },
  "required": [
    "grant_type",
    "client_id",
    "client_secret"
  ],
  "additionalProperties": false
}

=== solvo-ru/yard-apidoc/example_oauthtokenrequest.json
[
  {
    "grant_type": "authorization_code",
    "code": "Zc7yR3z6e8Ns98ho",
    "redirect_uri": "obhKPxD2y",
    "client_id": "Dh1P5P",
    "client_secret": "cfEDncs8wLO"
  },
  {
    "grant_type": "refresh_token",
    "code": "o4YVXVOwYAKrtHhoQ",
    "redirect_uri": "3hLqw",
    "client_id": "IIYvRgkxPajKoO4BC",
    "client_secret": "vyItuc052Iyxx"
  },
  {
    "grant_type": "authorization_code",
    "code": "kWgKKNA8",
    "redirect_uri": "XtnbzMwdlvXE",
    "client_id": "1Qz31",
    "client_secret": "QjXM5Q53rYBa"
  },
  {
    "grant_type": "authorization_code",
    "code": "4Q3DY6Hp94ui",
    "redirect_uri": "81HEReasfvDzU",
    "client_id": "ppoUlP7LAFjX4t",
    "client_secret": "YwU1LqtFMWya"
  },
  {
    "grant_type": "authorization_code",
    "code": "ioIzGMUp4w4nqFwrdqyC",
    "redirect_uri": "dvEq1HB",
    "client_id": "hZBPbySJFGA",
    "client_secret": "DTNksjX4f9"
  },
  {
    "grant_type": "refresh_token",
    "code": "dj9PzDyCEP",
    "redirect_uri": "m417vb9agcE7tvX",
    "client_id": "nO10x2oV4WsGz",
    "client_secret": "0WARMY8gIJK4JT2o8Rx4"
  },
  {
    "grant_type": "authorization_code",
    "code": "kJngTxhJ0",
    "redirect_uri": "I9MCu8ia",
    "client_id": "65Gvo4Vps7",
    "client_secret": "PeY5SB0c"
  },
  {
    "grant_type": "refresh_token",
    "code": "6Xr6kwJhR3YL1",
    "redirect_uri": "Ew3KpUuDqY6iNw",
    "client_id": "w430NFVYG9E3KJ97ardM",
    "client_secret": "JFj3pa77TzKfSZ"
  },
  {
    "grant_type": "refresh_token",
    "code": "IZyfDcEcAF",
    "redirect_uri": "k4u06heYTjHMo",
    "client_id": "lgyUsgZw",
    "client_secret": "q4xWjGWGoRyMyHoRFg"
  },
  {
    "grant_type": "authorization_code",
    "code": "qsIO2OCqYs7xP1lu",
    "redirect_uri": "mzMW41m6iC",
    "client_id": "KTD7fH7M629JbgH2",
    "client_secret": "ZmmvSSgkxlxMDXJ"
  }
]
